version: "3"
services:
  trafficcontrol:
    container_name: "Traffic Light Controller"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - MQTT_IP=1.2.3.4
      - TZ=America/Vancouver
      - INDICATORTOPIC=optional/command/topic/here
